### ISSUE TITLE
Pipeline for stage 1

### ISSUE THREAD

**Issue by chiragoel** [josebeo2016/BTS-Encoder-ASVspoof#4]
Hi, thank you for publishing the code. I am a bit confused about what is the correct pipeline I should follow for training the first stage model from scratch, given we have a folder with wav files.

**Comment by josebeo2016** [comment]
> Hi, thank you for publishing the code. I am a bit confused about what is the correct pipeline I should follow for training the first stage model from scratch, given we have a folder with wav files.

Hi,
For the first stage, please take a look at this repo: [https://github.com/josebeo2016/biosegment/](https://github.com/josebeo2016/biosegment/)

It is map to the `biosegment` folder in this source also. Currently, we support GMM (which was introduced in our ICASSP23 paper), and a light CNN - extended version for faster inference.

**Comment by chiragoel** [comment]
> > Hi, thank you for publishing the code. I am a bit confused about what is the correct pipeline I should follow for training the first stage model from scratch, given we have a folder with wav files.
> 
> Hi, For the first stage, please take a look at this repo: https://github.com/josebeo2016/biosegment/
> 
> It is map to the `biosegment` folder in this source also. Currently, we support GMM (which was introduced in our ICASSP23 paper), and a light CNN - extended version for faster inference.

Thanks for getting back! I was looking into this and what I don't understand is how do I get the segments and the corresponding labels `[breath, speech, silence]`?

**Comment by josebeo2016** [comment]
I have provided an example usage in [https://github.com/josebeo2016/biosegment/blob/main/breath_predict.ipynb](https://github.com/josebeo2016/biosegment/blob/main/breath_predict.ipynb). Please refer to that notebook

**Comment by chiragoel** [comment]
Oh is it that you do not train the GMM or the CNN model on the ASVspoof datasets and just use them for inference? Is my understanding correct?

**Comment by josebeo2016** [comment]
I trained segmentation model on self-making set derived from ASVspoof19 set (as described in my paper). The check points are available on github also.

**Comment by chiragoel** [comment]
Oh okay. Thanks a lot for the help!
