### ISSUE TITLE
Model models/trans_32concat/epoch_91.pth not found

### ISSUE THREAD

**Issue by parikshitmukherjee11** [josebeo2016/BTS-Encoder-ASVspoof#5]
Hi,

I was trying to use the Demo.ipynb but dont see the model weight. (models/trans_32concat/epoch_91.pth), can you please help

**Comment by josebeo2016** [comment]
Sorry about not sharing the pre-trained model. But you can train the model yourself before testing it with the Demo.ipynb.
If you have any difficulty on training the system, please create new issue
